---
provisioner:
  inventory:
    group_vars:
      all:
        caddy_config_mode: Caddyfile
        _caddy_service: caddy
        caddy_caddyfile: |
          localhost:80

          respond "Hello World!"
