---
provisioner:
  inventory:
    group_vars:
      all:
        caddy_config_mode: json
        _caddy_service: caddy-api
        caddy_json_config:
          apps:
            http:
              servers:
                example:
                  listen:
                    - ":80"
                  routes:
                    - handle:
                        - handler: "static_response"
                          body: "Hello World!"
