- name: Caddyfile is present
  template:
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfile_dest }}"
    owner: root
    group: root
    mode: "644"
  notify: Reload Caddy

- name: Caddy JSON/API service is stopped and disabled
  service:
    name: caddy-api
    state: stopped
    enabled: no

- name: Caddyfile service is started and enabled
  service:
    name: caddy
    state: started
    enabled: yes
