---
- name: Caddy is running
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop:
    - name: "{{ (caddy_config_mode == 'json') | ternary(_caddy_service_json, _caddy_service_caddyfile) }}"
      state: started
      enabled: true
    - name: "{{ (caddy_config_mode == 'json') | ternary(_caddy_service_caddyfile, _caddy_service_json) }}"
      state: stopped
      enabled: false

- name: Caddyfile is present
  template:
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfile_dest }}"
    owner: root
    group: root
    mode: "644"
  notify: Reload Caddy
