---
- name: Requirements are installed
  package:
    name: "{{ _package_requirements }}"
  when: (_package_requirements | default() )

- name: Import distro-specific tasks
  include_tasks: "{{ distrotask }}"
  when: (distrotask)
  vars:
    distrotask: "{{ lookup('first_found', params, errors='ignore') }}"
    params:
      skip: true
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'tasks/distro'

- name: Caddy is installed
  package:
    name: "{{ _caddy_package | default('caddy') }}"
    update_cache: true

- name: Caddy is running
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop:
    - name: "{{ (caddy_config_mode == 'json') | ternary(_caddy_service_json, _caddy_service_caddyfile) }}"
      state: started
      enabled: true
    - name: "{{ (caddy_config_mode == 'json') | ternary(_caddy_service_caddyfile, _caddy_service_json) }}"
      state: stopped
      enabled: false
