- name: Requirements are installed
  dnf:
    name:
      - dnf-command(copr)

- name: Pip requirements are installed
  pip:
    name: requests

- name: Caddy repository is enabled
  community.general.copr:
    name: "@caddy/caddy"

- name: Caddy is installed
  dnf:
    name: caddy
