---
- name: Requirements are installed
  package:
    name:
      - "{{ 'python3-requests' if ansible_python_version is version('3', '>=') else 'python-requests' }}"
      - dnf-command(copr)

- name: Caddy repository is enabled
  community.general.copr:
    name: "@caddy/caddy"

- name: Caddy is installed
  package:
    name: caddy
