---
- name: Package requirements are installed
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    update_cache: yes

- name: Pip requirements are installed
  pip:
    name: requests

- name: Caddy repo key is installed
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Caddy repository is enabled
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    owner: root
    group: root
    mode: "644"

- name: Caddy is installed
  apt:
    name: caddy
    update_cache: yes
