---
- name: Requirements are installed
  package:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - "{{ 'python3-requests' if ansible_python_version is version('3', '>=') else 'python-requests' }}"
    update_cache: yes

- name: Caddy repo key is installed
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Caddy repository is enabled
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    owner: root
    group: root
    mode: "644"

- name: Caddy is installed
  package:
    name: caddy
    update_cache: yes
