---
- name: Import distro-specific variables
  include_vars: "{{ distrovars }}"
  when: (distrovars)
  vars:
    distrovars: "{{ lookup('first_found', params, errors='ignore') }}"
    params:
      skip: true
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'vars/distro'

- name: Run Checks
  include_tasks: check.yml

- name: Perform Caddy install
  include_tasks: "install.yml"

- name: Run handlers
  meta: flush_handlers

- name: Gather service facts
  service_facts:

- name: Configure Caddy
  include_tasks: "config_{{ caddy_config_mode }}.yml"
  when:
    - caddy_apply_config
    - ansible_facts.services is search(lookup('vars', '_caddy_service_' ~ caddy_config_mode | lower))
